### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by kj7rrv** [kj7rrv/linux-distance-tracker#1]
This needs a GUI.

@Armen138 do you want to work on this?

**Comment by Armen138** [comment]
Yes, I'll start putting something together - are we ok with targeting gnome/phosh, or do you think you'd prefer kirigami (KDE/plasma-mobile)

Gnome-builder does  lot of the heavy lifting setting up the gui dependencies for gnome/gtk/libhandy, but it comes at a bit of a price - it will heavily favor distribution by flatpak, and add a build system by default(meson). Are we ok with that?

**Comment by kj7rrv** [comment]
I think that's okay, as long as Flatpak is not the only option. Could we still build packages for Arch/Manjaro, Mobian/Ubuntu Touch, and PostmarketOS?

I would prefer Gnome-based over KDE-based.

**Comment by kj7rrv** [comment]
I wonder if [Beeware](https://beeware.org/) works on PinePhone? It's a Python GUI toolkit that would also allow the possibility of an Android port.
