### ISSUE TITLE
All GPS acquisition needs to be async

### ISSUE THREAD

**Issue by Armen138** [kj7rrv/linux-distance-tracker#6]
For better integration with a gui front-end, we need all functions to accept a callback.
We should at least get:

* gps fix
* location
* speed
* climb speed
* altitude

Ideally, if we can, we should detect the loss of a gps fix and attempt to re-acquire it automatically

**Comment by kj7rrv** [comment]
Okay, I've never used async before, but I can try to figure it out. Does it actually need to use Python's async API, or just callbacks?

**Comment by kj7rrv** [comment]
Also, is it okay to use threads?

**Comment by Armen138** [comment]
using threads is fine - the main thing is not to block the main thread while we do gps things. The gui freezing would be a bad user experience!

**Comment by kj7rrv** [comment]
Okay. I'll start working on it tomorrow.

**Comment by kj7rrv** [comment]
The current API lets you check for messages from GPSD whenever you want. It just lets unread messages accumulate in the socket. Could the GUI just check for messages every second or something? Retrieving messages is a nonblocking operation; it just returns an empty list if there are none to receive.

**Comment by Armen138** [comment]
I can work with polling - I've modified the tracking script to enable this
