### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by kj7rrv** [kj7rrv/linux-distance-tracker#7]
We need a better name than "Linux Distance Tracker".

@Armen138 any ideas?

**Comment by Armen138** [comment]
I was rather hoping you'd have some ideas on this front.
I would want to avoid things that tie it to a specific activity, so avoid things like "walk" in the name, we also don't want to be too technical, though.

Some thoughts:
* Movement
* Move-tracker
* Outside

Ehm.. we can probably do better.

**Comment by kj7rrv** [comment]
WeMove?
 It clearly relates to movement, and "we" refers to it being a collaborative effort.

**Comment by kj7rrv** [comment]
I just thought, some people might think "We" in "WeMove" was referring to the Nintendo Wii, so that might not be a good choice.

**Comment by kj7rrv** [comment]
Maybe HowFar?

**Comment by Armen138** [comment]
I like HowFar, I think it implies self-improvement, which (at least for me) is a big goal for the application

**Comment by kj7rrv** [comment]
Okay, cool! Should I rename the repo?

**Comment by Armen138** [comment]
Sure, go for it
