### ISSUE TITLE
GPL, not X11 license

### ISSUE THREAD

**Issue by kj7rrv** [kj7rrv/linux-distance-tracker#9]
I just noticed that you used the X11 license on the GUI code. Would you mind changing it to GPL v3 to match what I wrote?

**Comment by Armen138** [comment]
I've removed the license headers automatically inserted by gnome-builder, the LICENSE file in the top level of the repo will serve as  the one source of truth this

**Comment by kj7rrv** [comment]
Looks good, thanks!

Closed by cffc60d521cd1a47fcab728bce280f86b3355954
